import express, { Request, Response, Application } from 'express';
import cors from 'cors';
import { expressConnectMiddleware } from "@connectrpc/connect-express";
import routes from "./routes.js";
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';

const app: Application = express();
const port: string | number = process.env.PORT || 3000;

app.use(cors({
  origin: (origin, callback) => {
    callback(null, true);
  },
  credentials: true
}));
app.use(express.json());

app.get('/health', (req: Request, res: Response): void => {
  res.json({ status: 'ok' });
});

import { Interceptor } from "@connectrpc/connect";

const errorLoggingInterceptor: Interceptor = (next) => async (req) => {
  try {
    return await next(req);
  } catch (err: any) {
    console.error("ConnectRPC Error:", err);
    throw err;
  }
};

app.use(expressConnectMiddleware({
  routes,
  options: {
    interceptors: [errorLoggingInterceptor]
  }
}));

// Serve SvelteKit frontend in production
if (process.env.NODE_ENV === 'production') {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  const sveltekitPath = path.resolve(__dirname, '../../frontend/build/handler.js');
  const clientPath = path.resolve(__dirname, '../../frontend/build/client');
  const prerenderedPath = path.resolve(__dirname, '../../frontend/build/prerendered');
  
  // Serve static assets generated by SvelteKit
  app.use(express.static(clientPath));
  app.use(express.static(prerenderedPath));
  
  try {
    const { handler } = await import(pathToFileURL(sveltekitPath).href);
    app.use(handler);
    console.log('Loaded SvelteKit production handler');
  } catch (error) {
    console.error('Failed to load SvelteKit production handler:', error);
  }
}

app.listen(port, (): void => {
  console.log(`Server is running on port ${port}`);
});

